# Generated by Django 4.1.7 on 2023-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=50)),
                ('officer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
            ],
        ),
    ]
