# Generated by Django 4.1.7 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluebookRenew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('district_code', models.CharField(max_length=20)),
                ('lot_no', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('vehicle_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('chit_number', models.CharField(max_length=30)),
            ],
        ),
    ]
