# Generated by Django 4.1.7 on 2023-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bluebookrenew_fine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TmsUser',
        ),
    ]
